/*
 * Copyright (c) 2012-2014 Alex de Kruijff
 * Copyright (c) 2014-2015 Specialisterren
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.mazarineblue.runner.swing;

import java.io.File;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alex de Kruijff {@literal <alex.de.kruijff@MazarineBlue.org>}
 */
public class AboutFrame
        extends javax.swing.JFrame {

    static ResourceBundle mazarineResource = ResourceBundle.getBundle(
            "MazarineBlue");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alexDeKruijffLabel;
    private javax.swing.JLabel buildDateLabel;
    private javax.swing.JLabel daanVerbiestLabel;
    private javax.swing.JLabel graphicalDesignLabel;
    private javax.swing.JLabel leadDeveloperLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel releaseDateLabel;
    private javax.swing.JLabel releaseVersionLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

    public AboutFrame() {
        initComponents();
    }

    private URL getLogoURL() {
        File logo = new File("logo.png");
        String path = logo.getPath();
        URL url = getClass().getClassLoader().getResource(path);
        return url;
    }

    private String getVersion() {
        try {
            return mazarineResource.getString("MazarineBlue.version");
        } catch (RuntimeException ex) {
            Logger.getLogger(AboutFrame.class.getName()).log(Level.SEVERE, null,
                                                             ex);
            return "Unable to fetch version";
        }
    }

    private String getBuildDate() {
        try {
            return mazarineResource.getString("MazarineBlue.buildDate");
        } catch (RuntimeException ex) {
            Logger.getLogger(AboutFrame.class.getName()).log(Level.SEVERE, null,
                                                             ex);
            return "Unable to fetch release date";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        releaseVersionLabel = new javax.swing.JLabel();
        leadDeveloperLabel = new javax.swing.JLabel();
        graphicalDesignLabel = new javax.swing.JLabel();
        alexDeKruijffLabel = new javax.swing.JLabel();
        daanVerbiestLabel = new javax.swing.JLabel();
        logoPanel = new ImagePanel(getLogoURL());
        buildDateLabel = new javax.swing.JLabel();
        releaseDateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About MazarineBlue");
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("MazarineBlue");

        versionLabel.setText("Version");

        releaseVersionLabel.setText(getVersion());

        leadDeveloperLabel.setText("Lead developer");

        graphicalDesignLabel.setText("Graphical design");

        alexDeKruijffLabel.setText("Alex de Kruijff");

        daanVerbiestLabel.setText("Daan Verbiest");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        buildDateLabel.setText("Build date");

        releaseDateLabel.setText(getBuildDate());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(versionLabel)
                            .addComponent(graphicalDesignLabel)
                            .addComponent(leadDeveloperLabel)
                            .addComponent(buildDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alexDeKruijffLabel)
                            .addComponent(daanVerbiestLabel)
                            .addComponent(releaseVersionLabel)
                            .addComponent(releaseDateLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(versionLabel)
                            .addComponent(releaseVersionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buildDateLabel)
                            .addComponent(releaseDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alexDeKruijffLabel)
                            .addComponent(leadDeveloperLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daanVerbiestLabel)
                            .addComponent(graphicalDesignLabel))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
