/*
 * Copyright (c) 2016 Alex de Kruijff <alex.de.kruijff@MazarineBlue.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.mazarineblue.mbt.gui.control;

import java.util.function.BiConsumer;
import java.util.function.Supplier;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 * A {@code ControlPanel} is a {@code JPanel} that contains two buttons allowing
 * the user to either accept or reject the content of another component.
 *
 * @author Alex de Kruijff <alex.de.kruijff@MazarineBlue.org>
 */
public class ControlPanel<T>
        extends JPanel {

    private static final long serialVersionUID = 1L;

    private T old;
    private Supplier<T> supplier;
    private BiConsumer<T, T> acceptAction;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton rejectButton;
    // End of variables declaration//GEN-END:variables

    public ControlPanel() {
        initComponents();
        acceptAction = (t, u) -> {};
    }

    public void setOld(T old) {
        this.old = old;
    }

    public void setAcceptSupplier(Supplier<T> supplier) {
        this.supplier = supplier;
    }

    public void setAcceptAction(BiConsumer<T, T> acceptAction) {
        this.acceptAction = acceptAction;
    }

    public void setAccept(JDialog owner, String actionText) {
        acceptButton.setAction(new ConsumerAction(owner, actionText, t -> {
                                              T next = supplier.get();
                                              if (next != null)
                                                  acceptAction.accept(old, next);
                                          }));
    }

    public void setReject(JDialog owner, String actionText) {
        rejectButton.setAction(new ConsumerAction(owner, actionText, t -> {}));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rejectButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();

        rejectButton.setText("Cancle");
        rejectButton.setName("rejectButton"); // NOI18N

        acceptButton.setText("OK");
        acceptButton.setName("acceptButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(acceptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rejectButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rejectButton)
                    .addComponent(acceptButton)))
        );
    }// </editor-fold>//GEN-END:initComponents
}
