@startuml
skinparam componentStyle uml2

[MazarineBlue-Main]-->[MazarineBlue-Plugins-Runners]
[MazarineBlue-Plugins-Feeds]-->[MazarineBlue-Engine-Core-EventDriven]
[MazarineBlue-Plugins-Feeds]-->[MazarineBlue-FileSystem]
[MazarineBlue-Plugins-Feeds]-->[MazarineBlue-Plugins-Utility]
[MazarineBlue-Plugins-Libraries]-->[MazarineBlue-Engine-Core-KeywordDriven]
[MazarineBlue-Plugins-Libraries]-->[MazarineBlue-Plugins-Utility]
[MazarineBlue-Plugins-Runners]-->[MazarineBlue-Plugins-Utility]

[MazarineBlue-Main]-0)-[MazarineBlue-Runners-ConsoleRunner]
[MazarineBlue-Main]-0)-[MazarineBlue-Runners-SwingRunner]
[MazarineBlue-Runners-ConsoleRunner]-->[MazarineBlue-Engine-Executors]
[MazarineBlue-Runners-ConsoleRunner]-->[MazarineBlue-Plugins-Runners]
[MazarineBlue-Runners-FitnesseRunner]-->[MazarineBlue-Runners-Threadrunner]
[MazarineBlue-Runners-FitnesseRunner]-->[MazarineBlue-Libraries-Fixtures]
[MazarineBlue-Runners-Threadrunner]-->[MazarineBlue-Engine-Executors]
[MazarineBlue-Runners-SwingRunner]-->[MazarineBlue-Engine-Executors]
[MazarineBlue-Runners-SwingRunner]-->[MazarineBlue-Pictures]
[MazarineBlue-Runners-SwingRunner]-->[MazarineBlue-Plugins-Runners]

[MazarineBlue-Engine-Executors]..>[MazarineBlue-Engine-Core-KeywordDriven]
[MazarineBlue-Engine-Executors]..>[MazarineBlue-FileSystem]
[MazarineBlue-Engine-Executors]-->[MazarineBlue-Engine-Logger]
[MazarineBlue-Engine-Executors]-->[MazarineBlue-Engine-VariableStore]
[MazarineBlue-Engine-Executors]-->[MazarineBlue-Plugins-Feeds]
[MazarineBlue-Engine-Executors]-->[MazarineBlue-Plugins-Libraries]

[MazarineBlue-Engine-Logger]-->[MazarineBlue-Engine-Core-EventNotifierLink]
[MazarineBlue-Engine-Logger]-->[MazarineBlue-Engine-Core-EventDriven]
[MazarineBlue-Engine-VariableStore]-->[MazarineBlue-Engine-Core-KeywordDriven]
[MazarineBlue-Engine-VariableStore]-->[MazarineBlue-Parser]

[MazarineBlue-Engine-Core-KeywordDriven]-->[MazarineBlue-Engine-Core-EventNotifierLink]
[MazarineBlue-Engine-Core-KeywordDriven]-->[MazarineBlue-Engine-Core-EventDriven]
[MazarineBlue-Engine-Core-EventNotifierLink]-->[MazarineBlue-EventNotifier]
[MazarineBlue-Engine-Core-EventDriven]-->[MazarineBlue-EventNotifier]

[MazarineBlue-Engine-Core-KeywordDriven]-0)-[MazarineBlue-Libraries-Awaitility]
[MazarineBlue-Engine-Core-KeywordDriven]-0)-[MazarineBlue-Libraries-Fixture]
[MazarineBlue-Engine-Core-KeywordDriven]-0)-[MazarineBlue-Libraries-Test]
[MazarineBlue-Engine-Core-EventDriven]-0)-[MazarineBlue-Feeds-ExcelFeed]
[MazarineBlue-Engine-Core-EventDriven]-0)-[MazarineBlue-Feeds-PlainTextFeed]

[MazarineBlue-Libraries-Awaitility]-->[MazarineBlue-Plugins-Libraries]
[MazarineBlue-Libraries-Fixture]-->[MazarineBlue-Plugins-Libraries]
[MazarineBlue-Libraries-Test]-->[MazarineBlue-Executors]
[MazarineBlue-Libraries-Test]-->[MazarineBlue-Toolkit]
[MazarineBlue-Toolkit]-->[MazarineBlue-Engine-Core-EventDriven]

[MazarineBlue-Feeds-ExcelFeed]-->[MazarineBlue-Engine-Core-KeywordDriven]
[MazarineBlue-Feeds-ExcelFeed]-->[MazarineBlue-Plugins-Feeds]
[MazarineBlue-Feeds-PlainTextFeed]-->[MazarineBlue-Engine-Core-KeywordDriven]
[MazarineBlue-Feeds-PlainTextFeed]-->[MazarineBlue-Plugins-Feeds]
@enduml
