/*
 * Copyright (c) 2016 Alex de Kruijff <alex.de.kruijff@MazarineBlue.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.mazarineblue.mbt.gui;

import static java.awt.EventQueue.invokeLater;
import java.util.Collection;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import static org.mazarineblue.mbt.gui.StringConstants.NEW_STATE;
import static org.mazarineblue.mbt.gui.StringConstants.NEW_TRANSITION;
import org.mazarineblue.mbt.gui.model.GraphModel;
import org.mazarineblue.mbt.gui.model.ModelListener;
import org.mazarineblue.mbt.gui.model.State;
import org.mazarineblue.mbt.gui.model.Transition;
import org.mazarineblue.mbt.gui.model.ui.JModelEditorPopup;
import org.mazarineblue.mbt.gui.model.ui.TableModelConvertor;

public class ModelEditorFrame
        extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private final GraphModel model;
    private final TableModelConvertor convertor;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane graphScrollPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu modelMenu;
    private javax.swing.JTabbedPane modelTabbedPane;
    private javax.swing.JMenuItem newStateMenuItem;
    private javax.swing.JMenuItem newTransitionMenuItem;
    private org.jdesktop.swingx.JXTable stateTransactionTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JComboBox<String> viewComboBox;
    private javax.swing.JLabel viewLabel;
    // End of variables declaration//GEN-END:variables

    public ModelEditorFrame(GraphModel model) {
        this.model = model;
        convertor = createConvertor(model);
        initComponents();
        addModelPopup();
    }

    private TableModelConvertor createConvertor(GraphModel model) {
        TableModelConvertor conv = new TableModelConvertor(model);
        model.addModelListener(conv);
        return conv;
    }

    private void addModelPopup() {
        JModelEditorPopup popup = new JModelEditorPopup(this, stateTransactionTable, convertor);
        stateTransactionTable.setComponentPopupMenu(popup);
        stateTransactionTable.getTableHeader().setComponentPopupMenu(popup);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewLabel = new javax.swing.JLabel();
        viewComboBox = new javax.swing.JComboBox<>();
        modelTabbedPane = new javax.swing.JTabbedPane();
        tableScrollPane = new javax.swing.JScrollPane();
        stateTransactionTable = new org.jdesktop.swingx.JXTable();
        graphScrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        modelMenu = new javax.swing.JMenu();
        newStateMenuItem = new javax.swing.JMenuItem();
        newTransitionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewLabel.setText("View");

        viewComboBox.setModel(getViewComboBoxModel(model));
        viewComboBox.setMinimumSize(new java.awt.Dimension(100, 20));
        viewComboBox.setName("viewComboBox"); // NOI18N
        viewComboBox.setPreferredSize(new java.awt.Dimension(100, 20));
        viewComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewComboBoxActionPerformed(evt);
            }
        });

        stateTransactionTable.setModel(convertor);
        stateTransactionTable.setName("stateTransactionTable"); // NOI18N
        tableScrollPane.setViewportView(stateTransactionTable);
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        stateTransactionTable.setDefaultRenderer(Object.class, centerRenderer);

        modelTabbedPane.addTab("Table", tableScrollPane);
        modelTabbedPane.addTab("Graph", graphScrollPane);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        modelMenu.setText("Model");

        newStateMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        newStateMenuItem.setMnemonic('s');
        newStateMenuItem.setText("New state");
        newStateMenuItem.setName("newStateMenuItem"); // NOI18N
        newStateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newState(evt);
            }
        });
        modelMenu.add(newStateMenuItem);

        newTransitionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, 0));
        newTransitionMenuItem.setText("New transition");
        newTransitionMenuItem.setName("newTransitionMenuItem"); // NOI18N
        newTransitionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTransition(evt);
            }
        });
        modelMenu.add(newTransitionMenuItem);

        jMenuBar1.add(modelMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewLabel)
                .addGap(18, 18, 18)
                .addComponent(viewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(modelTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLabel)
                    .addComponent(viewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(modelTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Helper methods for Generated Code">
    private ComboBoxModel<String> getViewComboBoxModel(GraphModel model) {
        Collection<String> views = model.getViews();
        DefaultComboBoxModel<String> swingModel = new DefaultComboBoxModel<>(views.toArray(new String[views.size()]));
        model.addModelListener(new ModelListener() {
            @Override
            public void addedStates(List<State> states) {
                Collection<String> views = model.getViews();
                // @TODO look here:
                swingModel.removeAllElements();
                views.stream().forEach(swingModel::addElement);
            }

            @Override
            public void addedTransitions(List<Transition> list) {
            }
        });
        return swingModel;
    }
    //</editor-fold>

    private void viewComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewComboBoxActionPerformed
        // @TODO Remove the next line
        Object selectedItem = viewComboBox.getSelectedItem();
        convertor.setView((String) viewComboBox.getSelectedItem());
    }//GEN-LAST:event_viewComboBoxActionPerformed

    private void newState(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newState
        StateDialog dialog = new StateDialog(this, NEW_STATE);
        dialog.setAcceptAction((oldState, newState) -> model.addState(newState));
        invokeLater(() -> dialog.setVisible(true));
    }//GEN-LAST:event_newState

    private void newTransition(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTransition
        TransitionDialog dialog = new TransitionDialog(this, NEW_TRANSITION);
        dialog.setAcceptAction((oldTransition, newTransition) -> model.addTransition(newTransition));
        dialog.setOptions(model.getStatesByView((String) viewComboBox.getSelectedItem()));
        invokeLater(() -> dialog.setVisible(true));
    }//GEN-LAST:event_newTransition
}
