@startuml
[MazarineBlue-EventBus] <- [MazarineBlue-Engine]
[MazarineBlue-Engine] <- [MazarineBlue-EngineExtended]

[MazarineBlue-EngineExtended] -(0- [MazarineBlue-PlainTextFeed]: Feed
[MazarineBlue-EngineExtended] -(0- [MazarineBlue-ExcelFeed]: Feed
[MazarineBlue-EngineExtended] -(0- [MazarineBlue-Toolkit]: Library

[MazarineBlue-EngineExtended] --> [MazarineBlue-FileSystem]
[MazarineBlue-EngineExtended] --> [MazarineBlue-VariableStore]

[MazarineBlue-ConsoleRunner] --> [MazarineBlue-EngineExtended]
[MazarineBlue-SwingRunner] --> [MazarineBlue-EngineExtended]
[MazarineBlue-ThreadRunner] --> [MazarineBlue-EngineExtended]
[MazarineBlue-FitnesseRunner] --> [MazarineBlue-ThreadRunner]

Fitnesse )-- [MazarineBlue-FitnesseRunner]
@enduml
