@startuml
[MazarineBlue-Parser] --> [junit]
[MazarineBlue-Parser] --> [junit-hierarchicalcontextrunner]
[MazarineBlue-Pictures] --> [junit]
[MazarineBlue-EventBus] ---> [junit]
[MazarineBlue-EventBus] --> [junit-hierarchicalcontextrunner]
[MazarineBlue-EventBus] --> [MazarineBlue-Utilities]
[MazarineBlue-Engine] ---> [junit]
[MazarineBlue-Engine] --> [junit-hierarchicalcontextrunner]
[MazarineBlue-Engine] --> [MazarineBlue-EventBus]
[MazarineBlue-Engine] --> [MazarineBlue-Utilities]
@enduml