@startuml
[MazarineBlue-EventBus] <- [MazarineBlue-Engine]
[MazarineBlue-Engine] <- [MazarineBlue-EngineExtended]

FeedPlugin )-- [MazarineBlue-PlainTextFeed]
[MazarineBlue-EngineExtended] -- LibraryPlugin
[MazarineBlue-EngineExtended] -- FeedPlugin

[MazarineBlue-EngineExtended] --> [MazarineBlue-FileSystem]
[MazarineBlue-EngineExtended] --> [MazarineBlue-VariableStore]

[MazarineBlue-ConsoleRunner] --> [MazarineBlue-EngineExtended]
[MazarineBlue-SwingRunner] --> [MazarineBlue-EngineExtended]
[MazarineBlue-ThreadRunner] --> [MazarineBlue-EngineExtended]
[MazarineBlue-FitnesseRunner] --> [MazarineBlue-ThreadRunner]

Fitnesse )-- [MazarineBlue-FitnesseRunner]
@enduml
